databases:
  - name: hunarmand-db
    plan: free
    databaseName: hunarmand
    user: hunarmand

services:
  - type: web
    name: hunarmand-project
    runtime: python
    rootDir: backend
    plan: free
    healthCheckPath: /health
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hunarmand-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_PHONE
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: ADMIN_NAME
        value: Админ Hunarmand
      - key: CORS_ORIGINS
        value: "*"
      - key: PYTHON_VERSION
        value: 3.11.9
